In [1]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
arr.shape = (2, 4)
arr
# array([[0, 1, 2, 3],
#        [4, 5, 6, 7]])

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
arr = np.arange(8)
arr_new = arr.reshape((2, 4), order='F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [5]:
arr = np.arange(8)
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr_trans = arr.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [7]:
arr = np.arange(3)
print(arr.shape)
# (3,)
arr_trans = arr.transpose()
print(arr_trans.shape)

(3,)
(3,)


In [8]:
nd_array =  np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [9]:
nd_array[1, 2]

3.0

In [10]:
nd_array[:2, 2]

array([1., 3.])

In [11]:
nd_array[1:, 2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [12]:
nd_array[:, 2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [30]:

nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)
nd_arr[:,2][::-1]

array([76, 13, 78], dtype=int16)

In [31]:
import numpy as np
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [32]:
vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [34]:
vec = np.array([3, 4])
length = np.linalg.norm(vec)
print(length)

5.0


In [13]:
import numpy as np
a = np.arange(12)
print(a)
a[::2] = 1 
print(a[::2])

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[1 1 1 1 1 1]


In [15]:
import numpy as np
def get_chess(a):
    chess = np.zeros((a,a))
    chess[1::2,::2] = 1
    chess[::2,1::2] = 1
   # chess2[::2] = 1
    
  
    return(chess)
print(get_chess(8))    


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [38]:
import numpy as np
def shuffle_seed(array):
    seed_rand=np.random.randint(0, 2**32 - 1, dtype=np.uint32)
    np.random.seed(seed_rand)
    np.random.shuffle(array)
    return(array,seed_rand)
array=[1,2,3,4,5]

print(shuffle_seed(array))

([2, 5, 3, 4, 1], 1229633503)


In [ ]:
import numpy as np
def shuffle_seed(array):
    seed_rand=np.random.randint(0, 2**32 - 1)
    np.random.seed(seed_rand)
    shuffled = np.random.permutation(array)
    return(shuffled ,seed_rand)
array=[1,2,3,4,5]

print(shuffle_seed(array))


In [64]:
import numpy as np
def min_max_dist(*vectors):
    distances=[]
    
    for i in range(len(vectors)-1):
    
        for j in range(i+1,len(vectors)):
         
            distances.append(np.linalg.norm(vectors[i]-vectors[j]))
    
    return (min(distances),max(distances))
vec1 = np.array([1,2,3])
vec2 = np.array([4,5,6])
vec3 = np.array([7, 8, 9])

print(min_max_dist(vec1, vec2, vec3,vec2*3))    

5.196152422706632
5.196152422706632
5.196152422706632
5.196152422706632
5.196152422706632
5.196152422706632
(5.196152422706632, 22.693611435820433)


In [68]:
import numpy as np
def any_normal(*vectors):
    
    
    for i in range(len(vectors)-1):
    
        for j in range(i+1,len(vectors)):
         
            if (np.dot(vectors[i],vectors[j])) == 0:
                return True
    
    return False

vec1 = np.array([2, 1])
vec2 = np.array([-1, 2])
vec3 = np.array([3,4])

print(any_normal(vec1, vec2, vec3))

True


In [74]:
import numpy as np
def get_loto(num):
    array=np.random.randint(1,101,(num,5,5))
    return array
print(get_loto(3))

[[[39 29 81 10 39]
  [88 49 89 78  4]
  [42 31 27 77 11]
  [74 56 39 34 19]
  [24 15 13 10 78]]

 [[72 55  9 71 13]
  [49 31 79 34 18]
  [ 1 43 30 26 52]
  [38 26 70 43 76]
  [21 57 38 54 29]]

 [[27 41 21 33 92]
  [62 23 60  7 21]
  [80 33  4 73 73]
  [13 67 15 84 10]
  [80 24 88  3  4]]]


In [94]:
import numpy as np
def get_unique_loto(num):
    choice=np.zeros((num,5,5))
    #print(choice)
    array=np.arange(1,101)
    for i in range(num):
        
        choice[i,:,:] = np.random.choice(array, size=(5,5), replace=False)
    return choice
print(get_unique_loto(4))

[[[ 61.   3.  42.  46.  47.]
  [ 77.  34.  12.  63.  78.]
  [ 98.   6.  88.   4.  25.]
  [ 17.  68.  43.  16.  60.]
  [ 35.  96.  37.  20.  11.]]

 [[ 73.  21.  28.  41.  79.]
  [ 23.  98.  92.   5.  29.]
  [ 34.  53.  58.  26.  61.]
  [ 52.  25.  82.  22.  36.]
  [ 55.  15.  87.  42.  50.]]

 [[ 29.  38.  22. 100.  97.]
  [ 26.  21.  10.  68.   1.]
  [ 42.  75.   5.  72.   9.]
  [ 76.  78.   2.  87.  23.]
  [  7.  96.  16.  14.  50.]]

 [[ 71.  54.  52.  40.  95.]
  [ 38.  83.  33.  16.  24.]
  [ 80.  86.  44.  21.  60.]
  [ 77.  57.  19.  70.  89.]
  [  6.  34.  66.  56.  36.]]]
